---
# -----------------------------------------------------------------------------
- hosts: all
# -----------------------------------------------------------------------------
  name: Disable Canary agent
  tasks:
# -----------------------------------------------------------------------------
  - name: Stop canary agent if already exists
    systemd:
      name: ct
      state: stopped
      enabled: no
    ignore_errors: yes
